# Generated by Django 5.0.7 on 2024-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=512, unique=True)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('legal_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_refresh_required', models.BooleanField(default=False)),
                ('unsuccessful_login_count', models.PositiveIntegerField(default=0)),
                ('is_feed_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
